project:
  type: website

website:
  title: "zlog"
  navbar:
    right:
      - text: "Home"
        href: https://wzbillings.com/
      - text: "Posts"
        href: index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      light: pulse
      dark: vapor
    css: styles.css

editor: source

